#!/usr/bin/env python3
"""Generate host adapters from the canonical Claude Code agent and command definitions.

ZeroProtocol keeps ONE canonical copy of everything. The 68 skills need no adapter at all -
`skills/<name>/SKILL.md` with `name` and `description` frontmatter is exactly what Claude Code,
Codex, OpenCode and Agent Plugins 1.0 all read, so they are symlinked as-is by
install-portable.sh.

Agents and slash commands are the parts whose FORMAT differs per host, so they are generated
here instead of being maintained four times:

    .claude/agents/*.md   ->  adapters/opencode/agents/*.md
    commands/*.md         ->  adapters/opencode/commands/*.md

    python3 scripts/build_adapters.py            # write them
    python3 scripts/build_adapters.py --check    # fail if they are stale (for CI)

WHY CODEX GETS NO ADAPTER HERE
Codex has no subagent definition format, and its custom prompts (`~/.codex/prompts/`) are
deprecated upstream in favour of skills. Codex therefore consumes the skills directly from
`~/.agents/skills/` and invokes them with `$skill-name`. Generating deprecated prompt files
would be shipping a dead format.

WHY HERMES GETS NO ADAPTER HERE
Hermes installs portable Agent Plugins 1.0 packages, and the repository root already IS one:
`plugin.json` plus `skills/<name>/SKILL.md`. Nothing to convert.

THE PERMISSION TRANSLATION IS THE POINT
Claude Code restricts a subagent by listing `tools:`. OpenCode does it by denying capabilities
in `permission:`. These are the same safety property expressed differently, and getting it wrong
would silently hand network access to an agent that is meant to have none - `zp-report-drafter`
in particular must never reach the network, because it drafts from evidence already on disk.
The mapping below is derived from each agent's declared Claude tool list, not hand-written.

Stdlib only.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AGENTS_SRC = REPO / ".claude" / "agents"
CMDS_SRC = REPO / "commands"
OC_AGENTS = REPO / "adapters" / "opencode" / "agents"
OC_CMDS = REPO / "adapters" / "opencode" / "commands"

GENERATED = ("<!-- GENERATED by scripts/build_adapters.py from {src} - "
             "edit that file, not this one -->")

# Claude tool -> the OpenCode permission keys it corresponds to. Only the capabilities that
# matter for the authorization boundary are modelled; read/glob/grep are always allowed.
NETWORK_KEYS = ("webfetch", "websearch")


def parse(text: str) -> tuple[dict, str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        raise ValueError("no YAML frontmatter")
    meta: dict[str, str] = {}
    for line in m.group(1).split("\n"):
        k = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if k:
            meta[k.group(1)] = k.group(2).strip()
    return meta, m.group(2)


def permissions_for(tools: str) -> dict[str, str]:
    """Translate a Claude `tools:` list into OpenCode `permission:` denials.

    Absence of a tool in Claude is a hard denial, so it becomes an explicit `deny` rather than
    being left unset - an unset permission inherits the global default, which may well be
    `allow`, and that would quietly widen the agent.
    """
    have = {t.strip().lower() for t in tools.split(",") if t.strip()}
    perms: dict[str, str] = {}
    if "bash" not in have:
        perms["bash"] = "deny"
    if "write" not in have and "edit" not in have:
        perms["edit"] = "deny"
    if "webfetch" not in have and "websearch" not in have:
        for k in NETWORK_KEYS:
            perms[k] = "deny"
    elif "webfetch" in have and "websearch" not in have:
        perms["websearch"] = "deny"
    return perms


def build_agents(check: bool) -> list[str]:
    stale = []
    OC_AGENTS.mkdir(parents=True, exist_ok=True)
    for src in sorted(AGENTS_SRC.glob("zp-*.md")):
        meta, body = parse(src.read_text(encoding="utf-8"))
        name = meta.get("name") or src.stem
        desc = meta.get("description", "")
        tools = meta.get("tools", "")
        perms = permissions_for(tools)

        lines = ["---", f"description: {desc}", "mode: subagent"]
        if perms:
            lines.append("permission:")
            for k, v in perms.items():
                lines.append(f"  {k}: {v}")
        lines.append("---")
        lines.append("")
        lines.append(GENERATED.format(src=f".claude/agents/{src.name}"))
        if perms:
            denied = ", ".join(sorted(perms))
            lines.append(f"<!-- Claude tools: {tools or 'inherited'} -> denied here: {denied} -->")
        lines.append("")
        lines.append(body.lstrip("\n"))
        out = "\n".join(lines)

        dst = OC_AGENTS / f"{name}.md"
        if check:
            if not dst.is_file() or dst.read_text(encoding="utf-8") != out:
                stale.append(str(dst.relative_to(REPO)))
        else:
            dst.write_text(out, encoding="utf-8")
    return stale


def build_commands(check: bool) -> list[str]:
    stale = []
    OC_CMDS.mkdir(parents=True, exist_ok=True)
    for src in sorted(CMDS_SRC.glob("zp-*.md")):
        meta, body = parse(src.read_text(encoding="utf-8"))
        desc = meta.get("description", "").strip().strip('"')
        # OpenCode takes the command id from the FILENAME, so `name:` is dropped. $ARGUMENTS
        # means the same thing in both hosts, so the body needs no rewriting.
        out = "\n".join([
            "---",
            f'description: "{desc}"',
            "---",
            "",
            GENERATED.format(src=f"commands/{src.name}"),
            "",
            body.lstrip("\n"),
        ])
        dst = OC_CMDS / src.name
        if check:
            if not dst.is_file() or dst.read_text(encoding="utf-8") != out:
                stale.append(str(dst.relative_to(REPO)))
        else:
            dst.write_text(out, encoding="utf-8")
    return stale


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any adapter is missing or out of date; write nothing")
    args = ap.parse_args()

    stale = build_agents(args.check) + build_commands(args.check)

    if args.check:
        if stale:
            print("build_adapters: these adapters are stale - re-run "
                  "`python3 scripts/build_adapters.py`:", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            return 1
        print("adapters up to date")
        return 0

    n_a = len(list(OC_AGENTS.glob("*.md")))
    n_c = len(list(OC_CMDS.glob("*.md")))
    print(f"  wrote {n_a} OpenCode agents -> {OC_AGENTS.relative_to(REPO)}")
    print(f"  wrote {n_c} OpenCode commands -> {OC_CMDS.relative_to(REPO)}")
    print("  skills need no adapter: SKILL.md is read as-is by every supported host")
    return 0


if __name__ == "__main__":
    sys.exit(main())
